In [1]:
import numpy as np

# K-means centroid method testing:

In [182]:
a = np.array([[1, 2, 3], [1, 2, 3]])
b = np.matrix([[0, 0], [5, 5]]).T
print(a)
print(a.shape)
print(b)

centroids = b
points = a
distances = []
for centroid in np.hsplit(centroids, centroids.shape[1]):
    distance_to_centroid = np.linalg.norm(points - centroid, axis=0)
    distances.append(distance_to_centroid)
distances = np.vstack(distances)
print(distances)
nearest_centroid = np.argmin(distances, axis=0)
print(nearest_centroid)
print('groups:')
for (index, centroid) in enumerate(np.hsplit(centroids, centroids.shape[1])):
    group_points = np.compress(nearest_centroid == index, points, axis=1)
    print(group_points)

[[1 2 3]
 [1 2 3]]
(2, 3)
[[0 5]
 [0 5]]
[[ 1.41421356  2.82842712  4.24264069]
 [ 5.65685425  4.24264069  2.82842712]]
[0 0 1]
groups:
[[1 2]
 [1 2]]
[[3]
 [3]]


# K-means main dispatch

In [98]:
centroid_indices = np.random.choice(points.shape[1], 2, replace=False)

for chunk in np.array_split(a, 2, axis=1):
    print(chunk)

[[1 2]
 [1 2]]
[[3]
 [3]]


# Recolor

In [177]:
c = np.matrix([0,1,2,1,0])
d = np.matrix([[0, 1, 0, 1, 0], [1, 0, 1, 0, 1]])
c = np.argmax(d, axis=0).reshape(1,5)
C = c.reshape(c.size)
print(C)
print(C.shape)
print(c)
print(c.shape)
print(a)

[[1 0 1 0 1]]
(1, 5)
[[1 0 1 0 1]]
(1, 5)
[[1 2 3]
 [1 2 3]]
[[1 0 1 0 1]]


In [181]:
print(a[:,C])
print(a[:,C].shape)
n = a[:,C]
n.reshape(10)
print(n)
print(n.shape)

[[[2 1 2 1 2]]

 [[2 1 2 1 2]]]
(2, 1, 5)
[[[2 1 2 1 2]]

 [[2 1 2 1 2]]]
(2, 1, 5)


In [128]:
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)
print(x1)
print(x2)
print(np.multiply(x1, x2))

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]]
[ 0.  1.  2.]
[[  0.   1.   4.]
 [  0.   4.  10.]
 [  0.   7.  16.]]


In [130]:
print(a[1,:])

[[1 2 3]]
