In [1]:
import numpy as np

# K-means centroid method testing:

In [51]:
a = np.matrix([[1, 2, 3], [1, 2, 3]])
b = np.matrix([[0, 0], [5, 5]]).T
print(a)
print(b)

centroids = b
points = a
distances = []
for centroid in np.hsplit(centroids, centroids.shape[1]):
    distance_to_centroid = np.linalg.norm(points - centroid, axis=0)
    distances.append(distance_to_centroid)
distances = np.vstack(distances)
print(distances)
nearest_centroid = np.argmin(distances, axis=0)
print(nearest_centroid)
print('groups:')
for (index, centroid) in enumerate(np.hsplit(centroids, centroids.shape[1])):
    group_points = np.compress(nearest_centroid == index, points, axis=1)
    print(group_points)

[[1 2 3]
 [1 2 3]]
[[0 5]
 [0 5]]
[[ 1.41421356  2.82842712  4.24264069]
 [ 5.65685425  4.24264069  2.82842712]]
[0 0 1]
groups:
[[1 2]
 [1 2]]
[[3]
 [3]]


# K-means main dispatch

In [90]:
centroid_indices = np.random.choice(points.shape[1], 2, replace=False)
print(centroid_indices)
centroids = points[:, centroid_indices]
print(centroids)

[1 2]
[[2 3]
 [2 3]]
